### ISSUE TITLE
Correct approach for reading data that has a size greater than the MTU?

### ISSUE THREAD

**Issue by lizziemac** [weliem/bluez_inc#11]
Howdy!
I have the following characteristic:
```cpp
    binc_application_add_characteristic(app, SERVICE_UUID,
                                        BIG_DATA_CHAR_UUID,
                                        GATT_CHR_PROP_READ);
 ```
 Where `BIG_DATA_CHAR_UUID` should returns data greater in length than the MTU. Unsurprisingly, this truncates when sent as one value; would the correct approach be to use the `GATT_CHR_PROP_NOTIFY` to send over to the central device?
 
I tried "chunking" the data and then making multiple calls to `binc_application_set_char_value` in my `on_local_char_read` callback, but only the last chunk wins.

If using notifications is the standard/expected behavior, do the notifies happen in the read callback? I'm pretty new to BLE so I appreciate any feedback.

Small disclaimer - the "big data" is about 750 bytes worth of data.

Thanks!

**Comment by weliem** [comment]
When doing a read operation the max length is 512 bytes. Normally, you'd use notifications to send a large amount of data. Simply chunk the data and send mutiple notifications. The receiver then needs to merge all chunks to form the complete data.

**Comment by lizziemac** [comment]
Thanks!
