### ISSUE TITLE
Get CompanyID and Manufacturer Data on discovery callback

### ISSUE THREAD

**Issue by mamigot-salto** [weliem/bluez_inc#23]
Hello! First of all I'd like to thank you for the awesome work you've done with this bluez_inc library. Thank you so much!

Ok, here is the issue I'm struggling with and hopefully you can help me with: I'd like to parse as a byte array the manufacturer data that is included within the advertisement packet from a peripheral device, but the `binc_device_get_manufacturer_data` method returns a pointer to a `GHashTable` which honestly I don't know how to process. What is the key that I should look for in that hash table so I can check the Company ID that is advertised? How can I parse the actual manufacture data that is included, is it a key or a value in the hash table? How is the data inserted in that hash table: as string or as byte array?

Thank you in advance

**Comment by weliem** [comment]
https://docs.gtk.org/glib/struct.HashTable.html

Use one of the GHastable functions to get the keys

**Comment by weliem** [comment]
The key is a *int and the value is a GByteArray
