### ISSUE TITLE
User-supplied log handler

### ISSUE THREAD

**Issue by charlesnicholson** [weliem/bluez_inc#28]
It would be very nice if the `bluez_inc` log handler took a user-supplied logging callback. In our setup we already have a full logging + diagnostics system, and I want to just plug `bluez_inc` logs into that.

If `bluez_inc` had something like:
```
typedef void (*log_cb)(LogLevel level, char const *tag, char const *msg);
void log_set_cb(log_cb cb);
```

Then `bluez_inc` could use its own logger by default, but if I provide my own all `bluez_inc` logs would only go through my callback.

(If you're interested, I could try a PR)

**Comment by weliem** [comment]
Yes, good idea, feel free to raise a PR!

**Comment by weliem** [comment]
Thx for the PR!
