### ISSUE TITLE
scope enums with `BINC_`

### ISSUE THREAD

**Issue by charlesnicholson** [weliem/bluez_inc#29]
`bluez_inc` provides enums in its public header files that have very generic and common names like `CONNECTED`, `STOPPED`, `STARTED`, etc.

Consider renaming them to `BINC_CONNECTED`, `BINC_STOPPED`, `BINC_STARTED`, etc.. so they don't collide with the application-owned "global" naming space.

(If you're interested, I could PR this)

**Comment by weliem** [comment]
Feel free to raise a PR!
