### ISSUE TITLE
Sending a notification to a specific subscriber

### ISSUE THREAD

**Issue by aacebedo** [weliem/bluez_inc#3]
Hi 

I am trying to create a small GATT service with a notification char allowing the server to send notification to a given node.
Is this possible with bluez_inc ? The `binc_application_notify` does not have a parameter to specify a destination node.

I don't see a way neither to get the address of a new subscriber in the callback function called when it happens

**Comment by martijnvanwelie** [comment]
Hi, in Bluez you can't notify to a specific central. It sends the notification to all connected devices.

**Comment by aacebedo** [comment]
Ok. Thank you for the response !
