### ISSUE TITLE
A couple more callbacks that I think should have a device object in them

### ISSUE THREAD

**Issue by bojennett** [weliem/bluez_inc#41]
In descriptor.h/c

typedef void (*OnDescReadCallback)(Descriptor *descriptor, const GByteArray *byteArray, const GError *error);
typedef void (*OnDescWriteCallback)(Descriptor *descriptor, const GByteArray *byteArray, const GError *error);

**Comment by weliem** [comment]
Fixed with [4f5715d](https://github.com/weliem/bluez_inc/commit/4f5715dec07688f1ffc35d0b64654c8d40fafdb5)
