### ISSUE TITLE
extern C for header files

### ISSUE THREAD

**Issue by bp1001** [weliem/bluez_inc#5]
Hi,

Thank you alot for your work.
Would it be possible to add the 

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

around the public header files to make it useable with c++? 

Preferably only put them around the function prototypes, not the includes. New versions of Glib apparently include C++ headers, so that putting the extern "C" around the glib includes generates compile errors.

Regards

**Comment by weliem** [comment]
Feel free to raise a PR! Then you can immediately check if it works as expected...

**Comment by bp1001** [comment]
I have added the changes locally now, everything seems to be working fine. I tried to push the changes to a new branch, but I do not seem to have the access rights to do so.

**Comment by weliem** [comment]
The way it works on Github is that you first 'fork' a repo. Then you make changes and raise a PR back to the original repo....

**Comment by weliem** [comment]
Thanks for the PR, closing this issue
