### ISSUE TITLE
binc_advertisement_set_rate?

### ISSUE THREAD

**Issue by abqjln** [weliem/bluez_inc#51]
For a peripheral (or central acting as a  peripheral), It looks like default is about 1 second, but I'd like to vary the advertisement rate under different conditions. 

Does something like "binc_advertisement_set_rate". Worried it is buried in the DBus configs. Thanks.

**Comment by weliem** [comment]
Good suggestion. I have implemented support for it in ce8063da3d8dc16840bbba1367e803986db31b08:

Use `binc_advertisement_set_interval(advertisement, 500, 500);`

Up to version 5.77 this will require experimental features to be enabled in main.conf.
