### ISSUE TITLE
Ubuntu 22.10: Discovering starts only after disable and enable the bluetooth adapter

### ISSUE THREAD

**Issue by freibauer** [weliem/bluez_inc#57]
I am using the example and adapted the filters for my device.
If the bluetooth adapter is disabled the example is not starting.
If the bluetooth adapter is enabled the example is starting the discovering but nothing
happens. If i disable and enable the adapter (with the Ubuntu-GUI) during discover 
the discovering is starting and the example is pairing.
Perhaps rfkill needs to be used in the correct moment, but i am not sure when.

**Comment by martijnvanwelie** [comment]
Please share relevant code and log.

**Comment by weliem** [comment]
try `rfkill unblock bluetooth` before running your app.....

**Comment by freibauer** [comment]
Many thanks for the quick replies. I get a start-script with the unblock to work.
Which looks like:
sudo hciconfig hci0 down; sudo rfkill unblock bluetooth ; sudo hciconfig up ; sudo ./central
