### ISSUE TITLE
Executing binc_characteristic_write() multiple times raises dlib-assertion G_IS_DBUS_CONNECTION

### ISSUE THREAD

**Issue by freibauer** [weliem/bluez_inc#72]
Hello everybody,

i have a issue writing multiple times a characteristic.
After exactly 12 times binc_characteristic_write() the dbus throws an exception:

(process:14758): GLib-GIO-CRITICAL **: 19:12:31.273: g_dbus_connection_call_finish_internal: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

I am using the binc_characteristic_write() to write data to a connected ble-modul which is 
in the u-blox SPP-mode.
 
I have used the initialization like in the examples without setting a callback:
```
    GVariant *result = g_dbus_connection_call_sync(dbusConnection,
                                                   BLUEZ_DBUS,
                                                   "/",
                                                   INTERFACE_OBJECT_MANAGER,
                                                   "GetManagedObjects",
                                                   NULL,
                                                   G_VARIANT_TYPE("(a{oa{sa{sv}}})"),
                                                   G_DBUS_CALL_FLAGS_NONE,
                                                   -1,
                                                   NULL,
                                                   &error);
```

Best regards,
Mathias

**Comment by weliem** [comment]
Ok, so this issue can be closed?

**Comment by freibauer** [comment]
Yes, it can be close.
Just one question about the delays. If i firing in the on_read() the next characteristic is there any
delay caused by the library or from the dbus ? The BLE-central is much quicker sending back frames.

**Comment by weliem** [comment]
I am not sure I understand your question. But the library is not adding delays anywhere. In general, there is no need to add delays.

**Comment by freibauer** [comment]
Many thanks for the quick reply and all your work.
